export default [
  {
    ignores: ['**/node_modules/**', '**/_bmad-output/**', '**/data/cftc-data.js', '**/data/cftc-data.json'],
  },
  {
    files: ['cot-free/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly', document: 'readonly', console: 'readonly',
        setTimeout: 'readonly', setInterval: 'readonly', clearTimeout: 'readonly',
        fetch: 'readonly', ResizeObserver: 'readonly',
        location: 'readonly', localStorage: 'readonly',
        addEventListener: 'readonly', removeEventListener: 'readonly',
        LightweightCharts: 'readonly',
        CFTC_DATA: 'readonly', MOCK_DATA: 'readonly', MOCK_COT_DATASET: 'readonly',
        ACTIVE_DATASET: 'writable', ACTIVE_DATA_SOURCE: 'writable',
        initChart: 'readonly', setChartData: 'readonly', destroyChart: 'readonly',
        loadCOTData: 'readonly', computeNet: 'readonly', computePercentile: 'readonly',
        computeWoW: 'readonly', getReportData: 'readonly', computeMarketMetrics: 'readonly',
        getAllMarketMetrics: 'readonly', searchMarkets: 'readonly',
        getChartData: 'readonly', getPriceHistory: 'readonly',
        renderScreener: 'readonly', sortScreener: 'readonly', formatNumber: 'readonly',
        initFilterPills: 'readonly', screenerCategoryFilter: 'writable',
        initApp: 'readonly', selectMarket: 'readonly', updateMarketDashboard: 'readonly',
        initSearch: 'readonly', selectSearchResult: 'readonly',
        initReportToggle: 'readonly', updateActiveStyles: 'readonly',
        chart: 'writable', series: 'writable',
        screenerSortColumn: 'writable', screenerSortAsc: 'writable',
        screenerReportType: 'writable', selectedMarketId: 'writable',
        activeReportType: 'writable',
        getCurrentWeek: 'readonly', getPrevWeek: 'readonly',
        refreshData: 'readonly', setLastUpdated: 'readonly', lastUpdated: 'writable',
        refreshUI: 'readonly', initRefresh: 'readonly',
        __COT_DATA_SOURCE: 'writable',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-undef': 'error',
      'no-var': 'warn',
      'prefer-const': 'warn',
    },
  },
  {
    files: ['cot-free/scripts/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        require: 'readonly', module: 'readonly', __dirname: 'readonly',
        __filename: 'readonly', process: 'readonly', console: 'readonly',
        setTimeout: 'readonly', Buffer: 'readonly',
        setImmediate: 'readonly', clearImmediate: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-undef': 'error',
      'no-var': 'warn',
      'prefer-const': 'warn',
    },
  },
];
